#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = kbuildsycoca6
exec = gsettings set org.gnome.desktop.interface gtk-theme "breeze"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar
exec-once = [worksapce 2 silent] steam
exec-once = [workspace 3 silent] vesktop
exec-once = [workspace 1] firefox
exec-once = killall StreamController
exec-once = [silent] flatpak run --branch=stable --arch=x86_64 --command=/app/bin/launch.sh com.core447.StreamController
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = hypridle
exec-once = syncthingtray-qt6
exec-once = dunst
